# Generated by Django 4.1.3 on 2022-11-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_juego', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('desarrollador', models.CharField(max_length=50)),
                ('generos', models.CharField(max_length=50)),
                ('plataformas', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.DateField()),
            ],
        ),
    ]
