# Generated by Django 4.1.3 on 2022-11-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeraApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuegos',
            name='id_juego',
        ),
        migrations.AddField(
            model_name='videojuegos',
            name='puntuacion',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
